### ISSUE TITLE
Unable to generate libxlite after compile

### ISSUE THREAD

**Issue by santrox** [x2bool/xlite#1]
I am trying to compile and generate the dll on windows. This seems to be generating a different dll file.

![image](https://user-images.githubusercontent.com/8513741/176114851-1159a93a-d92e-4f60-a8c9-ef87cf576676.png)

![image](https://user-images.githubusercontent.com/8513741/176115200-f077c2f4-f5b5-4f23-b102-efc6ebcbf55c.png)

**Comment by x2bool** [comment]
Hi!

I think this is expected. `cargo build` will produce xlite.dll on Windows.

**Comment by x2bool** [comment]
I reflected this info in README.md. Thanks for reporting.
