### ISSUE TITLE
Version 0.30.0 of rusqlite supports creating loadable extension

### ISSUE THREAD

**Issue by gwenn** [x2bool/xlite#15]
Hello,
For your information,
Since version [0.30.0](https://github.com/rusqlite/rusqlite/pull/1362), you should be able to use [rusqlite](https://docs.rs/rusqlite/latest/rusqlite/vtab/index.html) virtual table for your loadable extension.
Regards.

**Comment by x2bool** [comment]
Sounds good! Thanks for letting me know.
