### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by 0x6b** [x2bool/xlite#8]
As you might know I have forked your repository and tailored it for Google Sheet (as I've been using it at work.) I just want to say **thank you** for making the repo and [the blog article](https://sergey.khabibullin.com/sqlite-extensions-in-rust/) public. I really enjoyed reading it.

https://github.com/0x6b/libgsqlite

**Comment by x2bool** [comment]
Yes, I've seen your repo! Great job there! I am really excited to see your fork and looking forward to see how it will be adopted and used.

Thank you for the kind words)

**Comment by 0x6b** [comment]
Thanks! You can close this issue at any time👍
